# Generated by Django 5.2.7 on 2025-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlisting_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, default='listing_images/default.jpg', null=True, upload_to='listing_images/'),
        ),
    ]
